### ISSUE TITLE
一些小疑问

### ISSUE THREAD

**Issue by huakucha** [indulgeIn/YBTaskScheduler#1]
- (void)ybts_addTask:(YBTaskBlock)task priority:(YBTaskPriority)priority
_deque.pop_front();
高优先级的任务把低优先级的任务挤掉了 在cell这种UI任务场景下有用，但是其他场景低优先级的任务也是有执行的必要的啊

**Comment by indulgeIn** [comment]
maxNumberOfTasks 默认值为 NSUIntegerMax ，只要你不显式的限制数量就不会淘汰
