### ISSUE TITLE
`performSelector:withObject:afterDelay`  block the task

### ISSUE THREAD

**Issue by wangyingbo** [indulgeIn/YBTaskScheduler#3]
<img width="1083" alt="task" src="https://user-images.githubusercontent.com/12741589/63762502-73643300-c8f5-11e9-98ff-60d10a47dfd5.png">

 console log  task1 and task3, but the task2 is blocked

**Comment by indulgeIn** [comment]
这是 task2 不打印么？

**Comment by wangyingbo** [comment]
@indulgeIn 是的，task2一直没有打印

**Comment by wangyingbo** [comment]
还有一个疑惑，如果用FIFO模式，addTask三个网络请求的异步任务，这三个任务的回调顺序应该是乱序的吧？如果想要有顺序的拿到结果是不是还需要加信号量锁？

**Comment by indulgeIn** [comment]
任务的执行线程是可以指定的，如果是多个异步任务落地的顺序就算是不用组件控制也需要专门处理吧，而且网络请求这种理论上不需要用这个组件吧除非想延迟执行

**Comment by indulgeIn** [comment]
performSelector 在子线程执行需要开启 Runloop，在 perform 后面加一句 [[NSRunLoop currentRunLoop] run]; 试试。

**Comment by wangyingbo** [comment]
performSelector这个的确要开启runloop，是我疏忽了，感谢！

**Comment by wangyingbo** [comment]
网络请求这个场景，是因为多个请求任务间可能有依赖关系，所以可能需要顺序回调。
